apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "boundary.fullname" . }}
rules:
- apiGroups: ["batch","apps"]
  resources: ["jobs","deployments"]
  verbs: ["list", "get"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "boundary.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "boundary.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "boundary.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}